### ISSUE TITLE
paper citation

### ISSUE THREAD

**Issue by TQCAI** [electricbrainio/hypermax#10]
Hello, I am very interested in your research. Do you have a paper? I want to cite your work in my paper

**Comment by barsenault-creditsesame** [comment]
Hello @TQCAI No there is no published paper associatted with this work. There used to be a blog article you could cite but after selling the company, it was taken down by the new owners.

**Comment by genixpro** [comment]
@TQCAI I will not require any citations but might be able to help you if you absolutely need one

**Comment by genixpro** [comment]
email me a bradley.allen.arsenault@gmail.com

**Comment by genixpro** [comment]
I also think i put up a draft copy of the original blog article in a pull request against the hyperopt repository, but it never got merged
